// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelegramChainBot.Database;

#nullable disable

namespace TelegramChainBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714140000_UpdateSystemSettings")]
    partial class UpdateSystemSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TelegramChainBot.Database.Models.AdminAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("admin_accounts", (string)null);
                });

            modelBuilder.Entity("TelegramChainBot.Database.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActorAdminId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActorTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddressHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TelegramChainBot.Database.Models.Chain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClosedByAdminId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ClosedByTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatorTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeletedByAdminId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TelegramSyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("chains", (string)null);
                });

            modelBuilder.Entity("TelegramChainBot.Database.Models.ChainMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChainId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeftAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelegramFullName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChainId", "TelegramUserId")
                        .IsUnique();

                    b.ToTable("chain_members", (string)null);
                });

            modelBuilder.Entity("TelegramChainBot.Database.Models.ManagedChat", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovedByAdminId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorizationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatePolicy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultMaxMembers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsJoinEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxActiveChains")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId");

                    b.ToTable("managed_chats", (string)null);
                });

            modelBuilder.Entity("TelegramChainBot.Database.Models.ProcessedTelegramUpdate", b =>
                {
                    b.Property<int>("UpdateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceivedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UpdateId");

                    b.ToTable("processed_telegram_updates", (string)null);
                });

            modelBuilder.Entity("TelegramChainBot.Database.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultChainExpiryHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultCreatePolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultMaxMembers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeletedDataRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxActiveChainsPerChat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireMfaForSuperAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TelegramInitDataMaxAgeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnauthorizedChatBehavior")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByAdminId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WhitelistMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("system_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
